[workspace]
authors = ["Espen Trydal <espen@trydal.io>"]
channels = ["conda-forge"]
name = "pytorch-book"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
cuda-version = "12.1.*"

[pypi-dependencies]
torch = { version = "==2.1.2", index = "https://download.pytorch.org/whl/cu121" }
torchvision = { version = ">=0.6.2", index = "https://download.pytorch.org/whl/cu121" }

#[target.osx.pypi-dependencies]

